export const cardImages4 = [
    { "src": "./img/brown_panda.png", matched: false },
    { "src": "./img/genie.png", matched: false },
    { "src": "./img/goku.png", matched: false },
    { "src": "./img/homer.png", matched: false },
    { "src": "./img/iron_man.png", matched: false },
    { "src": "./img/kermit.png", matched: false },
    { "src": "./img/mario.png", matched: false },
    { "src": "./img/monster-blue.png", matched: false },
  ];

  export const cardImages6 = [
  { "src": "./img/bmo.png", matched: false },
  { "src": "./img/brown_panda.png", matched: false },
  { "src": "./img/finn.png", matched: false },
  { "src": "./img/genie.png", matched: false },
  { "src": "./img/orange.png", matched: false },
  { "src": "./img/pines.png", matched: false },
  { "src": "./img/goku.png", matched: false },
  { "src": "./img/gunter.png", matched: false },
  { "src": "./img/homer.png", matched: false },
  { "src": "./img/iron_man.png", matched: false },
  { "src": "./img/ice_king.png", matched: false },
  { "src": "./img/jake.png", matched: false },
  { "src": "./img/kermit.png", matched: false },
  { "src": "./img/lamp.png", matched: false },
  { "src": "./img/mario.png", matched: false },
  { "src": "./img/monster-blue.png", matched: false },
  { "src": "./img/smurf.png", matched: false },
  { "src": "./img/soos.png", matched: false },
  ];  
export const cardImages8 = [
  { "src": "./img/bmo.png", matched: false },
  { "src": "./img/brown_panda.png", matched: false },
  { "src": "./img/finn.png", matched: false },
  { "src": "./img/genie.png", matched: false },
  { "src": "./img/orange.png", matched: false },
  { "src": "./img/pines.png", matched: false },
  { "src": "./img/goku.png", matched: false },
  { "src": "./img/gunter.png", matched: false },
  { "src": "./img/homer.png", matched: false },
  { "src": "./img/iron_man.png", matched: false },
  { "src": "./img/ice_king.png", matched: false },
  { "src": "./img/jake.png", matched: false },
  { "src": "./img/kermit.png", matched: false },
  { "src": "./img/lamp.png", matched: false },
  { "src": "./img/mario.png", matched: false },
  { "src": "./img/monster-blue.png", matched: false },
  { "src": "./img/smurf.png", matched: false },
  { "src": "./img/soos.png", matched: false },
  { "src": "./img/beee.png", matched: false },
  { "src": "./img/cartman.png", matched: false },
  { "src": "./img/chess.png", matched: false },
  { "src": "./img/disney.png", matched: false },
  { "src": "./img/dolphin.png", matched: false },
  { "src": "./img/lumpy.png", matched: false },
  { "src": "./img/flutter.png", matched: false },
  { "src": "./img/minecraft.png", matched: false },
  { "src": "./img/prodigy.png", matched: false },
  { "src": "./img/starbucks.png", matched: false },
  { "src": "./img/sun.png", matched: false },
  { "src": "./img/walter.png", matched: false },
  { "src": "./img/twitter.png", matched: false },
  { "src": "./img/wendy.png", matched: false },
];