export const cardImages4 = [
    { "src": "./img/helmet-1.png", matched: false },
    { "src": "./img/potion-1.png", matched: false },
    { "src": "./img/ring-1.png", matched: false },
    { "src": "./img/scroll-1.png", matched: false },
    { "src": "./img/shield-1.png", matched: false },
    { "src": "./img/sword-1.png", matched: false },
    { "src": "./img/helmet-1.png", matched: false },
    { "src": "./img/potion-1.png", matched: false },
  ];
export const cardImages6 = [
    { "src": "./img/helmet-1.png", matched: false },
    { "src": "./img/potion-1.png", matched: false },
    { "src": "./img/ring-1.png", matched: false },
    { "src": "./img/scroll-1.png", matched: false },
    { "src": "./img/shield-1.png", matched: false },
    { "src": "./img/sword-1.png", matched: false },
    { "src": "./img/helmet-1.png", matched: false },
    { "src": "./img/potion-1.png", matched: false },
    { "src": "./img/helmet-1.png", matched: false },
    { "src": "./img/potion-1.png", matched: false },
    { "src": "./img/ring-1.png", matched: false },
    { "src": "./img/scroll-1.png", matched: false },
    { "src": "./img/shield-1.png", matched: false },
    { "src": "./img/sword-1.png", matched: false },
    { "src": "./img/helmet-1.png", matched: false },
    { "src": "./img/potion-1.png", matched: false },
    { "src": "./img/helmet-1.png", matched: false },
    { "src": "./img/potion-1.png", matched: false },
  ];  
export const cardImages8 = [
    { "src": "./img/helmet-1.png", matched: false },
    { "src": "./img/potion-1.png", matched: false },
    { "src": "./img/ring-1.png", matched: false },
    { "src": "./img/scroll-1.png", matched: false },
    { "src": "./img/shield-1.png", matched: false },
    { "src": "./img/sword-1.png", matched: false },
    { "src": "./img/helmet-1.png", matched: false },
    { "src": "./img/potion-1.png", matched: false },
    { "src": "./img/helmet-1.png", matched: false },
    { "src": "./img/potion-1.png", matched: false },
    { "src": "./img/ring-1.png", matched: false },
    { "src": "./img/scroll-1.png", matched: false },
    { "src": "./img/shield-1.png", matched: false },
    { "src": "./img/sword-1.png", matched: false },
    { "src": "./img/helmet-1.png", matched: false },
    { "src": "./img/potion-1.png", matched: false },
    { "src": "./img/helmet-1.png", matched: false },
    { "src": "./img/potion-1.png", matched: false },
    { "src": "./img/ring-1.png", matched: false },
    { "src": "./img/scroll-1.png", matched: false },
    { "src": "./img/shield-1.png", matched: false },
    { "src": "./img/sword-1.png", matched: false },
    { "src": "./img/helmet-1.png", matched: false },
    { "src": "./img/potion-1.png", matched: false },
    { "src": "./img/helmet-1.png", matched: false },
    { "src": "./img/potion-1.png", matched: false },
    { "src": "./img/ring-1.png", matched: false },
    { "src": "./img/scroll-1.png", matched: false },
    { "src": "./img/shield-1.png", matched: false },
    { "src": "./img/sword-1.png", matched: false },
    { "src": "./img/helmet-1.png", matched: false },
    { "src": "./img/potion-1.png", matched: false },
];